name: run-core-tests
jobs:
  test:
    name: Install and test Core
    strategy:
      max-parallel: 4
      matrix:
        os: [macos-11]
        python-version: [ 3.8, 3.9 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          architecture: x64
          python-version: ${{ matrix.python-version }}
      - name: Get pip cache dir
        id: pip-cache-dir
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: Cache pip
        uses: actions/cache@v3
        id: cache-pip
        if: startsWith(runner.os, 'Linux')
        with:
          path: ${{ steps.pip-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
      - name: Install java
        uses: actions/setup-java@v1
        with:
          java-version: '14.0.1' # The JDK version to make available on the path.
          java-package: jdk
          architecture: x64
      - name: Installation
        run:
          |
          pip install pyinstaller
          pip install --upgrade pip setuptools wheel
          pip install numpy>=1.20.1
          git clone https://github.com/CellProfiler/CellProfiler.git ~/cellprofiler
          pip install -e .[test]
          pip install -e ~/cellprofiler
      - name: Test
        run: pytest -k 'not test_load_objects and not test_load_single_object'
on:
  pull_request:
    types: [opened, reopened, ready_for_review, review_requested]
  push:
    branches:
      - 'master'
  workflow_dispatch:

